# Generated by Django 4.2.11 on 2025-03-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='biggest_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='biggest_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='highest_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='total_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='total_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='GameHistory',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackjack.playerprofile'),
        ),
    ]
