# Generated by Django 4.2.11 on 2025-03-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0002_transactionhistory_playerprofile_biggest_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
